### ISSUE TITLE
Solve subproject a

### ISSUE THREAD

**Issue by robperch** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-esesancr#13]
- [x] Solve question: Is there a correlation between a doctor's age and both his/her perception about the attractiveness of telemedicine in the future and his/her willingness to adopt a technological tool to enable services such as telemedicine?
- [x] Document procedure in personal readme

**Comment by esesancr** [comment]
Issue solved. Final Notebook and personal Readme for Subproject A uploaded.
